name: Check

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"

env:
  pnpm_CACHE_FOLDER: .cache/pnpm

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{ts,tsx,js,jsx,json}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: pnpm install

      - run: pnpm lint:check
